#!/bin/csh -f
##: run_dot - script to run the dot heuristic on a specified class
#: Usage: run_dot <class name>
#:        where <class name> is a string specifying a set of subdirectories
#:        of the data directory (enclosed in single or double quotes to
#:        prevent globbing)

if( "`setenv | fgrep DATA_DIRECTORY`" == "" ) then
     set DATA_DIRECTORY = $cwd/../data
endif
if( "`setenv | fgrep PROGRAM_DIRECTORY`" != "" ) then
     set path = ( ${PROGRAM_DIRECTORY} $path )
endif

if( $#argv != 1 ) then
    echo "Usage: $0 <class name>"
    echo "<class name> is a string specifying a set of subdirectories"
    echo "of the data directory (enclosed in single or double quotes to"
    echo "prevent globbing)"
    exit( 1 )
endif

cd $DATA_DIRECTORY
set class_list = `glob $1`
foreach dir ( $class_list )
    cd $DATA_DIRECTORY/$dir
    if( -e TR12 ) mv TR12 TR12.bak
    touch TR12
    foreach file ( *.dot )
        sbg_dot_cn $file >> TR12
    end
end

