#!/bin/csh -f
##: run_all - script to run all simple treatments on a specified class
## Usage: run_all <var>class name</var>
##        where <var>class name</var> is a string specifying a set of subdirectories
##        of the data directory (enclosed in single or double quotes to
##        prevent globbing)
## <br> $Revision: 1.1.1.1 $, $Author: mfms $, $Date: 2005/03/21 22:35:07 $

if( "`setenv | fgrep DATA_DIRECTORY`" == "" ) then
     set DATA_DIRECTORY = $cwd/../data
endif
if( "`setenv | fgrep PROGRAM_DIRECTORY`" != "" ) then
     set path = ( ${PROGRAM_DIRECTORY} $path )
endif

if( $#argv != 1 ) then
    echo "Usage: $0 <class name>"
    echo "<class name> is a string specifying a set of subdirectories"
    echo "of the data directory (enclosed in single or double quotes to"
    echo "prevent globbing)"
    exit( 1 )
endif

set trace = 1                   # some tracing, but not too much
endif
cd $DATA_DIRECTORY
set class_list = `glob $1`
foreach dir ( $class_list )
    if( $trace ) echo "Running treatments on class $dir"
    cd $DATA_DIRECTORY/$dir
    if( -e TR00 ) mv TR00 TR00.bak
    touch TR00
    foreach file ( *.dot )
        sbg_cn_eval $file $file.ORD >> TR00
    end
    foreach treatment ( 01 03 06 07 09 14 15 17 )
        if( $trace ) echo "  -- treatment $treatment"
        touch TR$treatment
        foreach file ( *.dot )
            if( $trace > 1 ) echo "    file = $file"
            set base = `basename $file .dot`
            sbg_treat -tr=$treatment $file $file.ORD
            if( "$status" ) exit $status
            sbg_cn_eval $file ${base}_tr00$treatment.ord >> TR$treatment
            rm -f ${base}_tr00$treatment.ord
        end
    end
end

#  [Last modified: 2004 09 28 at 15:52:36 GMT]
