#!/bin/csh -f
#: harvest_seeds - script to retrieve seed information used to generate
#:                 specified classes
#: Usage: harvest_seeds <class name> <output file>
#:        where <class name> is a string specifying a set of subdirectories
#:        of the data directory (enclosed in single or double quotes to
#:        prevent globbing) and <output file> is where the class names and
#:        the seeds are stored.

if( "`setenv | fgrep DATA_DIRECTORY`" == "" ) then
     set DATA_DIRECTORY = $cwd/../data
endif

if( $#argv != 2 ) then
    echo "Usage: $0 <class name> <output file>"
    echo "<class name> is a string specifying a set of subdirectories"
    echo "of the data directory (enclosed in single or double quotes to"
    echo "prevent globbing) and <output file> is where the class names and"
    echo "the seeds are stored."
    exit( 1 )
endif

set output_file = $cwd/$2
touch $output_file
cd $DATA_DIRECTORY
set class_list = `glob $1`
foreach dir ( $class_list )
    cd $DATA_DIRECTORY/$dir
    head -1 *_0001.dot | awk '{ print $2, $5, $6, $7; }' >> $output_file
end
